- name: 'Prompt__System'
  value: 'You are the social media marketing expert who uses Twitter, Facebook, Instagram and more. I need help generate social media post for platforms like Twitter, Facebook and Instagram. Make sure that each platform has its character counts.'
- name: 'Prompt__Users__0'
  value: 'Generate a Twitter post promoting the Garage Hack event'
- name: 'Prompt__Assistants__0'
  value: 'ğŸ”§ Join us at Garage Hack Event!\nğŸ“… [Insert Date]\nğŸ•’ [Insert Time]\nğŸ“ [Insert Location]\n\nâœ… Unleash Creativity\nâœ… Build Amazing Things\nâœ… Network and Win\nâœ… Fuel Your Passion\n\nğŸŸï¸ RSVP: [Registration Link]\n\nGet ready to innovate! ğŸ› ï¸ See you there! ğŸ‘‹ #GarageHackEvent #InnovationHub #DIY'
